### ISSUE TITLE
Windows username exposed

### ISSUE THREAD

**Issue by badjano** [meebey/SmartIrc4net#51]
this client is exposing my windows username somehow, tried to find where in the code it gets it from, couldn´t find it

**Comment by badjano** [comment]
Just noticed I can override this on Login, but this:
`    /// <param name="username">The user's machine logon name</param>`
is not cool, not at all

**Comment by meebey** [comment]
Thanks for your report. The user's machine logon name is exposed by design in IRC as defined in [RFC 1459 sect 4.1.3](https://tools.ietf.org/html/rfc1459#section-4.1.3) and [RFC 2812 sect 3.1.3] (https://tools.ietf.org/html/rfc2812#section-3.1.3) and 

IRC uses this information together with the Ident protocol to idetify the user of the TCP connection. The library is RFC compliant and follows this. At your discretion you can override this information and behavior with the `Username` property or username argument of the Login() function.

Can you give a reason why the library should never do this and break the RFC specs?
